### ISSUE TITLE
Bump sharp & imagemin-mozjpeg

### ISSUE THREAD

**Issue by katydecorah** [mapbox/appropriate-images#11]
I ran into an issue today installing appropriate-images. Based on the error, I believe the issue is stemming from sharp. See output of error below.

When I tried to npm install this repo, I saw the same error as when I tried to npm install the module. When I updated sharp, the error went away.

Also,  based on this warning:
> warning @mapbox/appropriate-images > imagemin-mozjpeg > mozjpeg > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

It may be good to also bump imagemin-mozjpeg.

I can create a PR to bump the versions, but I wanted to get a gut check.

Output:

```
katydecorah at mapbox in ~/Documents/GitHub/mapbox/mapbox-gl-js on approp-image [!?]
$ yarn install
yarn install v1.13.0
(node:68013) ExperimentalWarning: The fs.promises API is experimental
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning @mapbox/appropriate-images > imagemin-mozjpeg > mozjpeg > bin-build > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > raw-loader@1.0.0" has unmet peer dependency "webpack@^4.3.0".
warning " > rollup-plugin-unassert@0.2.0" has incorrect peer dependency "rollup@^0.56.2".
[5/5] 🔨  Building fresh packages...
[7/8] ⠠ fsevents
[-/8] ⠠ waiting...
[8/8] ⠠ gl
[4/8] ⠠ sharp
error /Users/katydecorah/Documents/GitHub/mapbox/mapbox-gl-js/node_modules/sharp: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/katydecorah/Documents/GitHub/mapbox/mapbox-gl-js/node_modules/sharp
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.1.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/katydecorah/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/katydecorah/Documents/GitHub/mapbox/mapbox-gl-js/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/katydecorah/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/katydecorah/.node-gyp/10.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/katydecorah/.node-gyp/10.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/katydecorah/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/katydecorah/.node-gyp/10.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/katydecorah/Documents/GitHub/mapbox/mapbox-gl-js/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Ignoring commonmarker-0.17.12 because its extensions are not built.  Try: gem pristine commonmarker --version 0.17.12
Ignoring commonmarker-0.17.11 because its extensions are not built.  Try: gem pristine commonmarker --version 0.17.11
gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/katydecorah/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/katydecorah/.nvm/versions/node/v10.1.0/bin/node" "/Users/katydecorah/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/katydecorah/Documents/GitHub/mapbox/mapbox-gl-js/node_modules/sharp
```

**Comment by davidtheclark** [comment]
If bumping the dependencies fixes this, let's do it. It'd be a good idea probably to bump as many as you can! It's been a while.
